# docker-compose.yml
version: '3.8'

services:
  web:
    build: . 
    image: ${DOCKER_USERNAME}/back-trader-bot:latest 
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL} 
      - SECRET=${JWT_SECRET_KEY}
    container_name: back_smallbutsteady
  